#!/bin/sh

# Configurar rutas para librerías y GI
HERE="$(dirname "$(readlink -f "$0")")"
export LD_LIBRARY_PATH="$HERE/usr/lib:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="$HERE/lib:${LD_LIBRARY_PATH}"
export GI_TYPELIB_PATH="$HERE/usr/lib/girepository-1.0:${GI_TYPELIB_PATH}"
export GI_TYPELIB_PATH="$HERE/lib/girepository-1.0:${GI_TYPELIB_PATH}"
export PYTHONPATH="$HERE/usr/lib/python3.11/site-packages:$PYTHONPATH"

# Ejecutar la aplicación Python
exec "$HERE/usr/bin/lnetmon.py"
